[build]
  command = "bun run build"
  publish = "dist" # Assuming 'dist' is your publish directory

[build.environment]
  # Specify the Bun version (optional, but good practice)
  # Check your local `bun --version` and use a matching or desired version
  BUN_VERSION = "1.1.20" # Example version, adjust if needed

# Override the default installation command
[plugins.inputs.install_command_override]
  command = "bun install --frozen-lockfile" 